source 'https://rubygems.org'

# General
gem 'rake'
gem 'foreman'
gem 'rack'
gem 'extensions'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'json', '~> 1.7.7'
gem 'multi_json'
gem 'git'
gem 'systemu'
gem 'rubyzip', :require => 'zip/zip'
gem 'resque', '~> 1.24.1'
gem 'sinatra-redis'